### ISSUE TITLE
Android build error method createAssetLoader in class JSBundleLoader cannot be applied to given types;

### ISSUE THREAD

**Issue by mdhanju** [Traviskn/react-native-threads#5]
Hi,

Getting build error when running `react-native run-android`

/node_modules/react-native-threads/android/src/main/java/com/reactlibrary/RNThreadModule.java:178: error: method createAssetLoader in class JSBundleLoader cannot be applied to given types;
    return JSBundleLoader.createAssetLoader(reactApplicationContext, "assets://threads/" + jsFileSlug + ".bundle");
                         ^
  required: Context,String,boolean
  found: ReactApplicationContext,String
  reason: actual and formal argument lists differ in length
1 error
:react-native-threads:compileReleaseJavaWithJavac FAILED

    "react": "16.0.0-alpha.12",
    "react-native": "0.47.2",
    "react-native-threads": "0.0.6",

Thanks

**Comment by Traviskn** [comment]
Hi @mdhanju, version 0.0.6 of this library will only work with react-native 0.48 on Android.  My apologies for not setting the peerDependency version correctly! 

Unfortunately every new version of react native for android introduces breaking changes in the APIs that this library uses.  I've just updated version 0.0.7 to work with changes introduced in react-native 0.49, and updated the peerDependency version to make that more clear
